import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

/* providers */
import { ThemeProvider } from "@/providers/theme-provider";
import { StoreProvider } from "@/providers/store-provider";

import Sidebar from "@/components/layout/sidebar";
import Topbar from "@/components/layout/topbar";

const plusJakartaSans = Plus_Jakarta_Sans({
	weight: ["200", "300", "400", "500", "600", "700", "800"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		/* surpressing hydration warning for next-themes + shadcn */
		<html lang="en" suppressHydrationWarning>
			<body className={`${plusJakartaSans.className} antialiased`}>
				<StoreProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="light"
						enableSystem
					>
						<Sidebar />
						<main className="w-full h-full pl-[19rem]">
							<Topbar />
							<div className="w-full h-full">{children}</div>
						</main>
					</ThemeProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
